language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: 1.58.1
    - rust: nightly
      env: CLIPPY
      script: |
          if rustup component add clippy-preview; then
              cargo clippy
          fi

script:
  - cargo build
  - cargo test
