language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: 1.28.0
    - rust: nightly
      env: CLIPPY
      script: |
          rustup component add clippy-preview || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
          cargo clippy -- -Dclippy

script:
  - cargo build
  - cargo test
