install:
  - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-1.22.1-i686-pc-windows-gnu.exe'
  - rust-1.22.1-i686-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V
  - git submodule update --init --recursive

build: false

test_script:
  - cargo test --verbose
